# Generated by Django 5.2.4 on 2025-07-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todoapp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.ImageField(default=0, upload_to='')),
            ],
            options={
                'db_table': 'todo_db',
            },
        ),
    ]
